name: social_feed_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shared_preferences:
  get: 4.6.1
  http:
  dio:
  flutter_svg:
  intl:
  url_launcher:
  auto_size_text:
  video_player:
  connectivity:
  fluttertoast:
  flutter_staggered_animations:
  image_picker:
  flutter_spinkit:
  cached_network_image:


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/videos/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf

        - asset: assets/fonts/Roboto-Black.ttf

        - asset: assets/fonts/Roboto-Medium.ttf

        - asset: assets/fonts/Roboto-Light.ttf




